# Generated by Django 5.0.6 on 2024-05-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_alter_student_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_id',
            new_name='student_id',
        ),
    ]
