# Generated by Django 5.0.6 on 2024-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=10)),
                ('major', models.CharField(choices=[('CSIT', 'Bsc.Csit'), ('BIT', 'Bit'), ('BCA', 'Bca'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('BIO', 'Biology'), ('PHY', 'Physics')], max_length=50)),
            ],
        ),
    ]
