# Generated by Django 5.0.6 on 2024-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0002_rename_first_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('+2', '+2 graduate'), ('BACHELOR', 'Bachelor'), ('MASTER', 'master')], default=1, max_length=50),
        ),
    ]
