# Generated by Django 5.0.6 on 2024-05-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0003_student_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
